### ISSUE TITLE
Cucumber Version Incompatibility: Package cucumber.api does not exist

### ISSUE THREAD

**Issue by saurabhbothra22** [CloudSmith-Delivery-Troubleshooting/spring-petclinic#78]
# CloudSmith Troubleshooting Summary
## Trigger details
| Workflow run  | Branch  | Commit  |
|---|---|---|
| [#15837153385](https://github.com/CloudSmith-Delivery-Troubleshooting/spring-petclinic/actions/runs/15837153385) |  ```main``` |  ```52410cc6e66c260ee2b2ba45eef533eb26b1623a``` |
----
### Issue 1

**Problem**: The root cause of the workflow failure is a Cucumber version incompatibility. The code is trying to use the old Cucumber API (cucumber.api package) but the project dependencies are using Cucumber 7.15.0 which uses a different package structure (io.cucumber). This mismatch was introduced in commit 52410cc6e66c260ee2b2ba45eef533eb26b1623a where the imports were changed from io.cucumber to cucumber.api, but the dependencies in the pom.xml were not updated accordingly.

**File**: ```src/test/java/org/springframework/samples/petclinic/integration/CucumberIntegrationTest.java```

**Error Log**:
```
[ERROR] /home/***/spring-petclinic/src/test/java/org/springframework/samples/petclinic/integration/CucumberIntegrationTest.java:[3,53] package cucumber.api does not exist\n[ERROR] /home/***/spring-petclinic/src/test/java/org/springframework/samples/petclinic/integration/CucumberIntegrationTest.java:[4,36] package cucumber.api.junit does not exist\n[ERROR] /home/***/spring-petclinic/src/test/java/org/springframework/samples/petclinic/integration/CucumberIntegrationTest.java:[5,22] cannot find symbol\n  symbol: class CucumberOptions
```

**Code snippet**:
```
package org.springframework.samples.petclinic.integration;\n\nimport org.junit.runner.RunWith;\nimport cucumber.api.CucumberOptions;\nimport cucumber.api.junit.Cucumber;\n\n@RunWith(Cucumber.class)\n@CucumberOptions(\n    features = "src/test/resources/features",\n    glue = "org.springframework.samples.petclinic.integration",\n    plugin = {"pretty"}\n)\npublic class CucumberIntegrationTest {\n}
```

**Solution Plan**:

1. Update the CucumberIntegrationTest.java file to use the correct imports for Cucumber 7.15.0:
```java
                   package org.springframework.samples.petclinic.integration;
                   
                   import org.junit.platform.suite.api.ConfigurationParameter;
                   import org.junit.platform.suite.api.IncludeEngines;
                   import org.junit.platform.suite.api.SelectClasspathResource;
                   import org.junit.platform.suite.api.Suite;
                   
                   import static io.cucumber.junit.platform.engine.Constants.GLUE_PROPERTY_NAME;
                   import static io.cucumber.junit.platform.engine.Constants.PLUGIN_PROPERTY_NAME;
                   
                   @Suite
                   @IncludeEngines("cucumber")
                   @SelectClasspathResource("features")
                   @ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "org.springframework.samples.petclinic.integration")
                   @ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "pretty")
                   public class CucumberIntegrationTest {
                   }
```
2. Update the CucumberSpringConfiguration.java file to use the correct imports:
```java
                   package org.springframework.samples.petclinic.integration;
                   
                   import io.cucumber.spring.CucumberContextConfiguration;
                   import org.springframework.boot.test.context.SpringBootTest;
                   import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
                   
                   @CucumberContextConfiguration
                   @SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
                   public class CucumberSpringConfiguration {
                   }
```
3. Update the PetClinicSteps.java file to use the correct imports:
```java
                   // Replace these imports:
                   import cucumber.api.DataTable;
                   import cucumber.api.java.Before;
                   import cucumber.api.java.en.Given;
                   import cucumber.api.java.en.Then;
                   import cucumber.api.java.en.When;
                   
                   // With these imports:
                   import io.cucumber.datatable.DataTable;
                   import io.cucumber.java.Before;
                   import io.cucumber.java.en.Given;
                   import io.cucumber.java.en.Then;
                   import io.cucumber.java.en.When;
```
4. Update the DataTable method calls in PetClinicSteps.java: - Replace `dataTable.asMaps(String.class, String.class)` with `dataTable.asMaps()`
5. Run the build to verify the changes:
```
                   ./mvnw clean package
```

----

### Issue 2

**Problem**: The workflow is configured to run on the \'cucumberVersionError\' branch for pull requests, which was intentionally set up to demonstrate this error. This indicates that the error was deliberately introduced for testing or demonstration purposes.

**File**: ```.github/workflows/deploy-to-ec2.yml```

**Error Log**:
```
2025-06-23T23:15:24.5868857Z out: [INFO] -------------------------------------------------------------\n2025-06-23T23:15:24.5869872Z out: [ERROR] COMPILATION ERROR : \n2025-06-23T23:15:24.5870778Z out: [INFO] -------------------------------------------------------------
```

**Code snippet**:
```
on:\n  push:\n    branches:\n      - \'**\'\n  pull_request:\n    branches: [ cucumberVersionError ]
```

**Solution Plan**:

1. If this error was intentionally created for demonstration purposes, you can either: - Keep the branch configuration as is if you want to continue using it for demonstration - Or change the branch configuration back to target the main branch:
```yaml
                   on:
                     push:
                       branches:
                         - \'**\'
                     pull_request:
                       branches: [ main ]
```
2. This change should be made after resolving the Cucumber version compatibility issues in the first finding.
3. Commit and push the changes to update the workflow configuration.

----

### Issue 3

**Problem**: The workflow is using the appleboy/ssh-action@v1.0.0 to run tests on an EC2 instance, but the tests are failing due to the Cucumber version incompatibility. The workflow is specifically configured to run the CucumberIntegrationTest, which is the test that\'s failing.

**File**: ```.github/workflows/deploy-to-ec2.yml```

**Error Log**:
```
2025-06-23T23:15:24.5868857Z out: [INFO] -------------------------------------------------------------\n2025-06-23T23:15:24.5869872Z out: [ERROR] COMPILATION ERROR : \n2025-06-23T23:15:24.5870778Z out: [INFO] -------------------------------------------------------------
```

**Code snippet**:
```
- name: Run Integration Tests on EC2\n        uses: appleboy/ssh-action@v1.0.0\n        with:\n          host: ${{ secrets.EC2_HOST }}\n          username: ${{ secrets.EC2_USER }}\n          key: ${{ secrets.EC2_SSH_KEY }}\n          script: |\n            cd spring-petclinic\n            # Run integration tests\n            ./mvnw test -Dtest=CucumberIntegrationTest
```

**Solution Plan**:

1. After fixing the Cucumber version compatibility issues in the first finding, ensure the workflow is using the correct Maven command to run the tests.
2. Consider adding a profile to run the tests to make it more explicit:
```yaml
                   - name: Run Integration Tests on EC2
                     uses: appleboy/ssh-action@v1.0.0
                     with:
                       host: ${{ secrets.EC2_HOST }}
                       username: ${{ secrets.EC2_USER }}
                       key: ${{ secrets.EC2_SSH_KEY }}
                       script: |
                         cd spring-petclinic
                         # Run integration tests with the integ profile
                         ./mvnw test -P integ
```
3. Consider adding error handling to the workflow to provide better feedback if tests fail:
```yaml
                   - name: Run Integration Tests on EC2
                     uses: appleboy/ssh-action@v1.0.0
                     with:
                       host: ${{ secrets.EC2_HOST }}
                       username: ${{ secrets.EC2_USER }}
                       key: ${{ secrets.EC2_SSH_KEY }}
                       script: |
                         cd spring-petclinic
                         # Run integration tests and capture the exit code
                         ./mvnw test -P integ || {
                           echo "Integration tests failed"
                           exit 1
                         }
```
